# -*- coding: utf-8 -*-
"""Gender classification

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1NO0LuuGYkMuAMdcCTon7SsAPyQS0wBCc
"""

#아래 코드 실행 안될시 주석코드 돌려볼것
#google colab
#from google.colab import drive
#drive.mount('/content/gdrive')

#!pip install nltk
import nltk
#nltk.download('book')

import pandas as pd
import spacy
from nltk.tokenize import word_tokenize
import numpy as np
from pandas import Series, DataFrame


def find_characters(data):
    characters=[]
    Me_character=['father', 'Father', 'Dad', 'dad', 'Daddy', 'daddy', 'Grandfather', 'grandfather', 'grandfa', 'Grandfa', "grandfa's", "Grandfa's", 'prince', 'Prince']
    Fe_character=['Stepmother', 'stepmother', 'Stepsisters', 'stepsisters', 'mother', 'Mother', 'mom', 'Mom', 'mommy', 'Mommy', 'Grandmother', 'grandmother', 'grandma', 'Grandma',  "grandma's", "Grandma's", 'princess', 'Princess']
    Gender_character= Me_character + Fe_character
    nlp=spacy.load('en_core_web_sm')
    contents=data['sentence']


    for s in data['sentence']:
      word_tokens = word_tokenize(s)
    for pronoun in word_tokens:
        if pronoun in Gender_character : characters.append(pronoun)


    for content in contents:
        if type(content)==float:continue
        doc = nlp(content)

        for ent in doc.ents:
            if (ent.label_=='ORG') or (ent.label_=='PERSON'):
                #print(ent.text) 
                if ent.text not in characters:characters.append(ent.text) 
            if (ent.text in Me_character) or (ent.text in Fe_character):
                if ent.text not in characters:characters.append(ent.text)
            #print(ent.text, ent.label_)
        #displacy.render(doc,style='ent',jupyter=True,options={'distance':90})
    characters=filter_characters(characters)
    return characters

def filter_characters(characters):
    filter_words=["Poof",'Knock','Hyap','Boo'] #의성어,의태어 거르기
    for filter_word in filter_words:
        if filter_word in characters:
            characters.remove(filter_word)
        
    return characters

def define_Gender(data):
  character_list=find_characters(data)
  Me_list=['He',' him','boy', ' his', 'man']
  Fe_list=['She',' her', 'girl', 'woman']
  Me_character=['father', 'Father', 'Dad', 'dad', 'Daddy', 'daddy', 'Grandfather', 'grandfather', 'grandfa', 'Grandfa', "grandfa's", "Grandfa's", 'prince', 'Prince']
  Fe_character=['Stepmother', 'stepmother', 'Stepsisters', 'stepsisters', 'mother', 'Mother', 'mom', 'Mom', 'mommy', 'Mommy', 'Grandmother', 'grandmother', 'grandma', 'Grandma',  "grandma's", "Grandma's", 'princess', 'Princess']
  pronoun_list=Fe_list + Me_list + find_characters(data)
  FM_list=[]
  for s in data['sentence']:
    word_tokens= word_tokenize(s)
    for pronoun in word_tokens:
        if pronoun in pronoun_list : FM_list.append(pronoun)

  
  character_FM = pd.DataFrame({'Name':find_characters(data)})
  character_FM['M']=0
  character_FM['F']=0
  character_FM['Gender']=0
  character_FM = character_FM.astype({'F': 'int'})
  character_FM = character_FM.astype({'M': 'int'})
  character_FM = character_FM.astype({'Name': 'str'})
  character_FM = character_FM.astype({'Gender': 'int'})


  for i in range(0, len(FM_list)-1):
    if FM_list[i] in character_list:
      if FM_list[i-1] in Fe_list:
        character_FM.loc[character_FM['Name']==FM_list[i], 'F']+=1
      if FM_list[i+1] in Fe_list: 
        character_FM.loc[character_FM['Name']==FM_list[i], 'F']+=1

      if FM_list[i-1] in Me_list: 
        character_FM.loc[character_FM['Name']==FM_list[i], 'M']+=1
      if FM_list[i+1] in Me_list: 
        character_FM.loc[character_FM['Name']==FM_list[i], 'M']+=1

      #남자1, 여자2 , 미정0
  for i in range(0, len(character_FM.index)):
    if character_FM.loc[i,'M'] > character_FM.loc[i,'F']:
      character_FM.loc[i, 'Gender']=1
    if character_FM.loc[i,'M'] < character_FM.loc[i,'F']:
      character_FM.loc[i, 'Gender']=2
    if character_FM.loc[i,'Name'] in Me_character:
      character_FM.loc[i, 'Gender']=1
    if character_FM.loc[i,'Name'] in Fe_character:
      character_FM.loc[i, 'Gender']=2

  return character_FM 





data=pd.read_csv('/content/gdrive/MyDrive/LittleRedRidingHood.csv', encoding='cp949')
data.columns=['sentence', 'posNeg', 'bi_posNeg']
data=data.dropna(how='any')
print(define_Gender(data))
print('\n')

data=None
data=pd.read_csv('/content/gdrive/MyDrive/Cinderella.csv', encoding='cp949')
data.columns=['sentence', 'posNeg', 'bi_posNeg']
data=data.dropna(how='any')
print(define_Gender(data))
print('\n')

data=None
data=pd.read_csv('/content/gdrive/MyDrive/HanselandGretel.csv', encoding='cp949')
data.columns=['sentence', 'posNeg', 'bi_posNeg']
data=data.dropna(how='any')
print(define_Gender(data))
print('\n')