# -*- coding: utf-8 -*-
"""Gender classification

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1NO0LuuGYkMuAMdcCTon7SsAPyQS0wBCc
"""

#아래 코드 실행 안될시 주석코드 돌려볼것
#google colab
#from google.colab import drive
#drive.mount('/content/gdrive')

#!pip install nltk
#nltk.download('book')

import nltk
import pandas as pd
import spacy
from nltk.tokenize import word_tokenize
import numpy as np
from pandas import Series, DataFrame


def find_characters(data):
    characters=[]
    nlp=spacy.load('en_core_web_sm')
    contents=data['sentence']

    for content in contents:
        if type(content)==float:continue
        doc = nlp(content)

        for ent in doc.ents:
            if (ent.label_=='ORG') or (ent.label_=='PERSON'):
                #print(ent.text) 
                if ent.text not in characters:characters.append(ent.text) 
            #print(ent.text, ent.label_)
        #displacy.render(doc,style='ent',jupyter=True,options={'distance':90})
    characters=filter_characters(characters)
    return characters

def filter_characters(characters):
    filter_words=["Poof",'Knock','Hyap','Boo'] #의성어,의태어 거르기
    for filter_word in filter_words:
        if filter_word in characters:
            characters.remove(filter_word)
        
    return characters

def define_Gender(data):
  character_list=find_characters(data)
  Fe_list=['She','her', 'girl']
  Me_list=['He','him','boy']
  pronoun_list=['He','She','him', 'her', 'girl', 'boy'] + find_characters(data)
  FM_list=[]
  for s in data['sentence']:
    word_tokens= word_tokenize(s)
    for pronoun in word_tokens:
        if pronoun in pronoun_list : FM_list.append(pronoun)

  
  character_FM = pd.DataFrame({'Name':find_characters(data)})
  character_FM['M']=0
  character_FM['F']=0
  character_FM['Gender']=0
  character_FM = character_FM.astype({'F': 'int'})
  character_FM = character_FM.astype({'M': 'int'})
  character_FM = character_FM.astype({'Name': 'str'})
  character_FM = character_FM.astype({'Gender': 'int'})

  
  for i in range(0, len(FM_list)-1):
    if FM_list[i] in character_list:
      if FM_list[i-1] in Fe_list:
        character_FM.loc[character_FM['Name']==FM_list[i], 'F']+=1
      if FM_list[i+1] in Fe_list: 
        character_FM.loc[character_FM['Name']==FM_list[i], 'F']+=1

      if FM_list[i-1] in Me_list: 
        character_FM.loc[character_FM['Name']==FM_list[i], 'M']+=1
      if FM_list[i+1] in Me_list: 
        character_FM.loc[character_FM['Name']==FM_list[i], 'M']+=1

      #여자1, 남자-1, 중립0
  for i in range(0, len(character_FM.index)):
    if character_FM.loc[i,'M'] > character_FM.loc[i,'F']:
      character_FM.loc[i, 'Gender']= -1
    elif character_FM.loc[i,'M'] < character_FM.loc[i,'F']:
      character_FM.loc[i, 'Gender']=1
    else: character_FM.loc[i,'Gender']=0

  return character_FM 


data=pd.read_csv('/content/gdrive/MyDrive/LittleRedRidingHood.csv', encoding='cp949')
data.columns=['sentence', 'posNeg', 'bi_posNeg']
data=data.dropna(how='any')
print(define_Gender(data))
print('\n')

data=None
data=pd.read_csv('/content/gdrive/MyDrive/Cinderella.csv', encoding='cp949')
data.columns=['sentence', 'posNeg', 'bi_posNeg']
data=data.dropna(how='any')
print(define_Gender(data))
print('\n')

data=None
data=pd.read_csv('/content/gdrive/MyDrive/HanselandGretel.csv', encoding='cp949')
data.columns=['sentence', 'posNeg', 'bi_posNeg']
data=data.dropna(how='any')
print(define_Gender(data))
print('\n')